spring:
  application:
    name: feign-task
  zipkin:
    base-url: http://127.0.0.1:9411/
    discoveryClientEnabled: false
    sender:
      type: web  # 设置使用http的方式传输数据
  sleuth:
    sampler:
      percentage: 1.0

server:
  context-path: /
  port: 6060

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:5050/eureka/,http://127.0.0.1:5051/eureka/,http://127.0.0.1:5052/eureka/

#feign的配置项:
feign:
  client:
    config:
      default:
        connectTimeout: 5000  # 指定Feign客户端连接提供者的超时时限   取决于网络环境
        readTimeout: 5000   # 指定Feign客户端从请求到获取到提供者给出的响应的超时时限  取决于业务逻辑运算时间
  hystrix:
    enabled: false #启动feign的断路器功能
  compression:
    request:
      min-request-size: 2048
      mime-types:
        - text/xml, application/xml, application/json
    response:
      enabled: true