server:
  port: 7070

spring:
  application:
    name: gateway-zuul

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:5050/eureka/,http://127.0.0.1:5051/eureka/,http://127.0.0.1:5052/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

zuul:
  prefix: /gateway
  ignored-services: '*'
  sensitive-headers: Cookie,Set-Cookie,Authorization # 指定全局敏感header，默认是Cooki,Set-Cookie,Authorization
  routes:
    task-route: #路由名称,自定义
      path: /zuul-task/** # service-id对应的路径
      service-id: feign-task


