spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.nz.test.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:config/mybatis-config.xml

#eureka:
#  client:
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://127.0.0.1:5050/eureka/,http://127.0.0.1:5051/eureka/,http://127.0.0.1:5052/eureka/