spring:
  application:
    name:  task-dao-jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        # hbm2ddl:
        # auto: create
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        # format_sql: true
    show-sql: true

#  kafka:
#    bootstrap-servers: 127.0.0.1:9092
#    producer:
#      retries: 0
#      batch-size: 16384
#      buffer-memory: 33554432
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      group-id:  consumer-default
#      auto-commit-interval: 100
#      auto-offset-reset: earliest
#      enable-auto-commit: true
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    listener:
#      concurrency: 3

server:
  port: 9091
  servlet:
    context-path: /
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#    prefer-ip-address: true
#    healthcheck:
#      enabled: true
#  client:
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://127.0.0.1:8000/eureka/,http://127.0.0.1:8001/eureka/,http://127.0.0.1:8002/eureka/