server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
  datasource:
    # 配置数据源
    driver-class-name: com.mysql.jdbc.Driver  # mysql数据库驱动
    type: com.alibaba.druid.pool.DruidDataSource # druid连接池
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC
    username: root # 数据库登录账户
    password: root # 数据库登录密码
    useGlobalDataSourceStat: true
    druid:
      # 连接池配置
      initial-size: 5 # 初始化大小
      max-active: 50  # 最大
      min-idle: 5     # 最小
      max-wait: 60000 # 配置获取连接等待超时时间
      # 是否缓存preparedStatement,也就是PSCache(官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开,打开PSCache,并且指定每个连接上PSCache的大小)
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 如果不配validationQuery项,则下面三项配置无用
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      min-evictable-idle-time-millis: 300000   # 配置一个连接在池中最小生存的时间,单位是毫秒
      log-abandoned: true
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能;慢SQL记录
      web-stat-filter:
        enabled: true
        url-pattern: /*
        session-stat-enable: true # 是否启用session的统计功能
        session-stat-max-count: 1000 # 监控最大session数，默认是1000
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*' # 设置不统计哪些URL
        profile-enable: true # 是否启用监控单个Url调用的sql列表
        principalSessionName: session_user_key # 使druid当前session的用户是谁，session_user_key是你保存到session中的sessionName
        principalCookieName: cookie_user_key # 使druid只当当前的user是谁,cookie_user_key是你保存在cookie中的cookieName
      # druid管理页配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        deny: 192.168.1.100
      # 配置StatFilter
      filters: stat,wall,slf4j # 配置监控统计拦截的filters,去掉后监控界面sql无法统计,'wall'用于防火墙
      filter:
        stat:
          enabled: true
          db-type: mysql
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 2000
        # 配置WallFilter
        wall:
          db-type: mysql
          enabled: true
          config:
            delete-allow: true
            drop-table-allow: false
            multi-statement-allow: true
            delete-where-alway-true-check: true
            delete-where-none-check: true
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true

  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.chaoqi.springboot_mybatisplus.domain

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  config-location: classpath:mybatis-config.xml # mybatis的config文件位置配置
  mapper-locations: classpath:mapper/*.xml     # 表的xml文件位置配置
  type-aliases-package: com.nz.test.domain.**

